### PR TITLE
Post meeting fixes

### LINKED ISSUE #11: 500 Internal Server Error when trying to retreive some items
Hello,

Since the unofficial iiif.archivelab.org API seems to have been shut down, I'm trying to migrate to iiif.archive.org. But some items don't seem to work, and I can't figure out why. For example:

`https://iiif.archive.org/iiif/0-0-1/manifest.json` is fine, but

`https://iiif.archive.org/iiif/0-._20211206/manifest.json` doesn't work.

Thanks!

### LINKED ISSUE #14: Handle arrays for metadata['description'] in addMetadata()
Flagged by @barmintor on the IIIF community call:

>Want to flag this - working: https://iiif.archive.org/iiif/2/annualreport00carn_14/manifest.json
> broken: https://iiif.archive.org/iiif/3/annualreport00carn_14/manifest.json

At a quick glance, looks like it's failing because metadata['description'] is an array: https://archive.org/metadata/annualreport00carn_14

### LINKED ISSUE #15: Collections routes need redirect
As identified on the [IIIF Slack](https://iiif.slack.com/archives/C0AL6BU76/p1694642459434369?thread_ts=1694633247.632699&cid=C0AL6BU76) following the IIIF/IA community call, we're missing a redirect route for collections manifest generation to match the routing we do for regular manifest generation.

I believe the following additions to app.py should cover it, but I welcome review by others:

```python
@app.route('/iiif/<identifier>/collection.json')
@cache.cached(timeout=cache_timeouts["long"], forced_update=cache_bust)
def collection(identifier):
    return redirect(f'/iiif/3/{identifier}/collection.json', code=302)

@app.route('/iiif/<identifier>/<page>/collection.json')
@cache.cached(timeout=cache_timeouts["long"], forced_update=cache_bust)
def collectionPage(identifier, page):
    return redirect(f'/iiif/3/{identifier}/{page}/collection.json', code=302)
```

### LINKED ISSUE #17: Internal Server Error when fetching manifests
Maybe too early too soon (too enthusiastic about this!) but I tested out the new manifests for the IA items on the [Gilly's Library](https://www.gillys-library.org) website that I maintain. Only a single one gave a successful response (see the list below); the rest returned an Internal Server Error. Books come from the collections of the [Getty Research Institute](https://archive.org/details/getty), and one from the [Smithsonian Libraries and Archives](https://archive.org/details/@smithsonianlibraries).

https://iiif.archive.org/iiif/gri_33125008667756/manifest.json
https://iiif.archive.org/iiif/gri_33125012605529/manifest.json
https://iiif.archive.org/iiif/gri_33125008297349/manifest.json
https://iiif.archive.org/iiif/gri_33125008667582/manifest.json
https://iiif.archive.org/iiif/gri_33125009324597/manifest.json
https://iiif.archive.org/iiif/gri_33125008626158/manifest.json
https://iiif.archive.org/iiif/gri_33125009548336/manifest.json 🎉
https://iiif.archive.org/iiif/gri_33125010859516/manifest.json
https://iiif.archive.org/iiif/gri_33125011111214/manifest.json
https://iiif.archive.org/iiif/gri_33125010907554/manifest.json
https://iiif.archive.org/iiif/gri_33125011183007/manifest.json
https://iiif.archive.org/iiif/ioannisbaptista00pira/manifest.json (Smithsonian)
https://iiif.archive.org/iiif/gri_33125008262210/manifest.json
https://iiif.archive.org/iiif/gri_33125008527570/manifest.json
https://iiif.archive.org/iiif/gri_33125011113459/manifest.json
https://iiif.archive.org/iiif/gri_33125009747607/manifest.json
https://iiif.archive.org/iiif/gri_33125008448025/manifest.json
https://iiif.archive.org/iiif/gri_33125012907867/manifest.json
https://iiif.archive.org/iiif/altedenkmalerde00winc/manifest.json
https://iiif.archive.org/iiif/gri_33125010864763/manifest.json
https://iiif.archive.org/iiif/gri_33125012602732/manifest.json
https://iiif.archive.org/iiif/gri_33125010908289/manifest.json
https://iiif.archive.org/iiif/gri_33125010884381/manifest.json
https://iiif.archive.org/iiif/veuesdeversaille00swid/manifest.json
https://iiif.archive.org/iiif/02413153.5462.emory.edu/manifest.json
https://iiif.archive.org/iiif/gri_33125011118912/manifest.json
https://iiif.archive.org/iiif/segmentanobilium00perr/manifest.json
https://iiif.archive.org/iiif/gri_33125008676393/manifest.json

### PR DESCRIPTION
**Pull request by digitaldogsbody**
- Brings in Rob's changes from the IA production deploy
- Re-remove the url2ia route and function
- Add fix for unquoted non-ascii filenames - closes #11 
- Add fix for multiple descriptions - closes #14, closes #17 
- Add redirect for collections to versioned endpoint - closes #15 
- Add redirect from manifest.json -> collection.json where appropriate (also in #15)
- Updates collections to use unversioned identifiers (identified in IIIF slack linked in #15)

### CODE REVIEW

**Comment by glenrobson** [comment]
Josh is going to push a fix for the breaking test to get it to deploy.

**Comment by glenrobson** [comment]
Glen to add tests and then hopefully we can merge to main.

**Comment by glenrobson** [comment]
Also add Josh's page direction:

https://github.com/internetarchive/iiif/issues/9#issuecomment-1741339561

**Comment by glenrobson** [comment]
Closing in favour of https://github.com/internetarchive/iiif/pull/39 with branch name without underscores.

**Review by hadro — APPROVED** [review]

**Pull request merged**
